default_language_version:
  python: python3.11
  node: 18.16.1 # latest LTS up-to-date
repos:
  # apply to all files
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: requirements-txt-fixer
  # HTML and JSON, MARKDOWN format
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v3.0.0-alpha.4'
    hooks:
      - id: prettier
        name: prettier markdown
        args: ['--config', '.markdownlint.json']
        types: [markdown]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v3.0.0-alpha.4'
    hooks:
      - id: prettier
        name: prettier frontend
        args: ['--config', '.prettierrc.json']
        types_or: [json, yaml]
  # Python
  # pre-commit runs all the remote repo from an isolated virtualenv,
  # the venvs are cached between executions and applied only to mewly modified files (~/.cache/pre-commit)
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.2.1
    hooks:
      - id: autoflake
        args: [--remove-all-unused-imports, --remove-unused-variables, -ir, .]
        types: [python]
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [--settings-path, setup.cfg, .]
        types: [python]
  - repo: https://github.com/psf/black
    rev: 23.9.0
    hooks:
      - id: black
        args: [--config, pyproject.toml, .]
        types: [python]
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args: [--config, setup.cfg, .]
        types: [python]
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.5
    hooks:
      - id: codespell
        name: codespell
        description: Checks for common misspellings in text files.
        entry: codespell
        language: python
        types: [text]
