AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SQS Partial Batch Response

Globals:
  Function:
    Runtime: python3.11
    MemorySize: 256
    Timeout: 5
    Environment:
      Variables:
        POWERTOOLS_SERVICE_NAME: sqs-batch-processing
        LOG_LEVEL: DEBUG

Resources:
  SQSBatchFunction:
    Type: AWS::Serverless::Function
    Properties:
      Events:
        Batch:
          Type: SQS
          Properties:
            Queue: !GetAtt SQSBatchDLQQueue.Arn
            FunctionResponseTypes:
              - ReportBatchItemFailures
      FunctionName: sqs-batch-processing
      Handler: sqs_batch_processing.app.lambda_handler
      CodeUri: ../src/services/sqs_batch_processing
      # TODO - Update policy with least privilege
      Policies:
        - AdministratorAccess

  SQSBatchDLQ:
    Type: AWS::SQS::Queue

  SQSBatchDLQQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 30
      SqsManagedSseEnabled: true
      RedrivePolicy:
        maxReceiveCount: 2
        deadLetterTargetArn: !GetAtt SQSBatchDLQ.Arn
