name: Python Workflow

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - develop
      - master
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]

    steps:
      # Check out the last commit and set the repo version as environment variable
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Prepare the Python environment and run pytest and pylint
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: |
            **/requirements-dev.txt
            **/setup.cfg

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements-dev.txt

      - name: Run flake8
        run: flake8 --config setup.cfg

      - name: Run mypy
        run: mypy .

      - name: Run pytest
        run: pytest --color=yes -n 8 -rAfv --log-level=WARNING --cov=. --cov-report=xml --show-capture=no

      - name: Show Coverage
        run: coverage report -m
